---
- hosts: localhost
  become: yes
  tasks:
  	- name: Install Apache2
  	  apt:
  	  	name: apache2
  	  	state: latest

  	- name: Edit the index file 
  	  lineinfile:
  	  	path: /var/www/html/index.html
  	  	line: Hello this line is written by Ansible - lineinfile module
  	  	state: present

