---
- hosts: ubuntu-server
  become: yes
  tasks:
  	- name: Install PIP 
  	  apt:
  	  	name: pip
  	  	state: latest

    - name: Install ansible
      command: pip install ansible

    - name: Install boto3
      command: pip install boto3

    - name: upgrade ansible
      command: pip install --upgrade ansible
